### ISSUE TITLE
FAQ entry on publisher location

### ISSUE THREAD

**Issue by riddella** [ge1789/docs-adding-new-records#1]
Address this question:

"The only question I had was about the publisher location. I did some digging and found that Blackwoods was in Edinburgh, for example, but I didn't know if there was an easier way of finding publisher location to make sure it's a UK novel. I'm thinking about the less obvious publishers like Bentley and not New York."

**Comment by leschnei** [comment]
I found a long list of British publishers here: http://www.jacobabbott.com/English/index.html

**Comment by tjbassett** [comment]
I updated the documentation.
