### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by leschnei** [ge1789/docs-adding-new-records#2]
With translations, do I put the original author under the last name column, and the translator in the notes section?

**Comment by tjbassett** [comment]
Yes: the author should always be the original author of the work.  Translators should go in the notes section.  If possible list the language, e.g., "Translated from the French by John Doe"

**Comment by riddella** [comment]
This might merit being added to the FAQ section of the documentation.

**Comment by riddella** [comment]
Fixed. I update the docs.
