### ISSUE TITLE
Variations

### ISSUE THREAD

**Issue by leschnei** [ge1789/docs-adding-new-records#3]
I think I know the answer to this but I want to be sure that variations of books fall under the same rule for editions? At the top of page 5, there are a bunch of Aesop Fables tweaked by other authors. My initial thought is that none of them would be included.

**Comment by riddella** [comment]
@tjbassett Do you have any thoughts?

**Comment by tjbassett** [comment]
That is correct.  Ancient works like the classics or old authors like Chaucer or Shakespeare should be ignored.
